export const asyncFetch=async(method,url,extra_headers={},extra_body=null,csrf=null,isJWT=false)=>{
    try {
        const headers={
            ...extra_headers
        }
        if(isJWT){
            headers["X-Authorization"]=localStorage.getItem("token")
        }
        if(csrf){
            headers["X-CSRFTOKEN"]=csrf
        }
        const options={
            method,
            credentials:"include",
            headers
        }
        if(extra_body){
            options["body"]=extra_body
        }
        
        const response=await fetch(url,options)
        const result=await response.json()
        return {error:null,result}
    } catch (error) {
        console.log(error)
        if(error.cause?.origin=="manual"){
            //means it is generated by user
            console.log(error.message)

        }
        else{
            console.log("System Issue Occured")
        }
        return {error,result:null}
    }
}